repos:
  - repo: local
    hooks:
      - id: betterleaks
        name: Betterleaks Scan
        language: docker_image
        entry: ghcr.io/betterleaks/betterleaks:latest protect --staged -v
        pass_filenames: false