---
name: linting

on: 
  push:
  pull_request:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Node.js Environment
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Dependencies
        working-directory: srcs/reqs/node
        run: npm ci

      - name: Run Linter
        working-directory: srcs/reqs/node
        run: npm run lint

  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up python Environment
        uses: actions/setup-python@v7

      - name: Install linter
        run: pip install sqlfluff

      - name: Lint models
        run: "sqlfluff lint models"

  lint-dockerfile:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true

  lint-yaml:
    name: Lint YAML Configs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Yamllint
        uses: ibiqlik/action-yamllint@v3
