name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        working-directory: srcs/reqs/node
        run: npm install eslint

      - name: Run Linter
        working-directory: srcs/reqs/node
        run: npm run lint